version: '3.9'

services:
  db:
    image: postgres:16
    container_name: postgres_django_ejemplo
    environment:
      POSTGRES_DB: db_vrisa
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
